### ISSUE TITLE
感謝妳所做的工作，我想請問妳做了什麽改變讓anynet支持pytorch1.10+呢，另外為什麽選擇refine函數代替原文中的SPNet，這樣會讓最後的精度變差嗎？我運行test_loop.py時產生的視差圖是正常的，但深度圖除了第壹張，其余都是類似黃、藍、紫這樣的純色塊，請問這是什麽原因呢？

### ISSUE THREAD

**Issue by flyxuexi** [gyes00205/AnyNet#1]

**Comment by gyes00205** [comment]
Hi @flyxuexi,

1. 使用 pytorch 1.10+ 的原因
因為原本的 repo 是用 0.4.0 寫的，但他無法支援一些高版本的 cuda，因此我才想說用當時比較新的 pytorch 改寫，不過基本的一些 coding 方式，應該不會和 0.4.0 相差太多。
2. 為甚麼使用 refine 取代 SPNet
因為 SPNet 還需要額外用 `nvcc`  的指令去編譯其他程式，當時可能因為 cuda 版本問題，所以無法編譯，因此才會改用 python 去實作 refine layer，像這種 refine layer 在 MVSNet 也有出現過。
3. 視差圖是正常的，但深度圖似乎顯示有問題
我在想可能是 focal * baseline / disp 出來的深度太小或太大，導致畫出來的圖片怪怪的(你也可以把他 normalize 0~256 之間再畫出來)，不過其實深度和視差只是反比關係，因此如果只是要觀察的話，用視差圖觀察就好了。
4. 為何要確保圖像長、寬被16整除
因為在用 convolution 提取 feature map 時，也會 down sample 圖片大小，為了避免在 down sample 的過程中會有無法整除的情況，因此我有 padding 圖片，這個方式在大部分的 stereo matching 研究都會做，有些可能是用 resize 的方式，但目的是一樣的。

希望這些回答有幫助到你。
Thanks

**Comment by flyxuexi** [comment]
> Hi @flyxuexi,
> 
> 1. 使用 pytorch 1.10+ 的原因
>    因為原本的 repo 是用 0.4.0 寫的，但他無法支援一些高版本的 cuda，因此我才想說用當時比較新的 pytorch 改寫，不過基本的一些 coding 方式，應該不會和 0.4.0 相差太多。
> 2. 為甚麼使用 refine 取代 SPNet
>    因為 SPNet 還需要額外用 `nvcc`  的指令去編譯其他程式，當時可能因為 cuda 版本問題，所以無法編譯，因此才會改用 python 去實作 refine layer，像這種 refine layer 在 MVSNet 也有出現過。
> 3. 視差圖是正常的，但深度圖似乎顯示有問題
>    我在想可能是 focal * baseline / disp 出來的深度太小或太大，導致畫出來的圖片怪怪的(你也可以把他 normalize 0~256 之間再畫出來)，不過其實深度和視差只是反比關係，因此如果只是要觀察的話，用視差圖觀察就好了。
> 4. 為何要確保圖像長、寬被16整除
>    因為在用 convolution 提取 feature map 時，也會 down sample 圖片大小，為了避免在 down sample 的過程中會有無法整除的情況，因此我有 padding 圖片，這個方式在大部分的 stereo matching 研究都會做，有些可能是用 resize 的方式，但目的是一樣的。
> 
> 希望這些回答有幫助到你。 Thanks

嗯嗯，感謝妳不吝賜教！
